name: test1

on:
  push:
    branches:
      - master  # Deploy on pushes to the master branch
  pull_request:
    branches:
      - master  # Run on pull requests to the master branch



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Specify the .NET SDK version

      # Restore and build the application
      - name: Restore and Build
        run: dotnet publish BlazorWasmGames3.csproj -c Release -o release --nologo

      # changes the base-tag in index.html from '/' to 'BlazorWasmGames3' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to BlazorWasmGames3
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorWasmGames3\/" \/>/g' release/wwwroot/index.html
    
      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot  # Path to the published Blazor WebAssembly files
